(package! catppuccin-theme)
(package! org-modern-indent :recipe (:host github :repo "jdtsmith/org-modern-indent"))
(package! olivetti :recipe (:host github :repo "rnkn/olivetti"))

(package! websocket)
(unpin! org-roam)
(package! org-roam-ui)

(package! org-web-tools)
(package! super-save)
(package! org-auto-tangle)
(package! chezmoi)
(package! org-transclusion)
(package! windresize)
(package! deadgrep)
