#+title: Config
#+property: header-args :tangle config.el
#+auto_tangle: t
#+startup: show2levels

* Doom appearance settings
** Font
#+begin_src emacs-lisp
(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
     doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
#+end_src
** Doom theme
#+begin_src emacs-lisp
(setq doom-theme 'catppuccin)
(setq catppuccin-flavor 'mocha)
#+end_src
** Doom style of line numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type 'relative)
#+end_src
* Org-mode
** auto-save when quitting org agenda
#+begin_src emacs-lisp
(advice-add 'org-agenda-quit :before 'org-save-all-org-buffers)
#+end_src
** auto-save all org agenda buffers
#+begin_src emacs-lisp
(add-hook 'auto-save-hook 'org-save-all-org-buffers)
#+end_src
** org-mode: TODO states
#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
      '((sequence "TODO(t)" "WAITING(w)" "PROJ(p)" "SOMEDAY(s)" "|" "DONE(d)" "CANCELED(c)")))
)
#+end_src
** org-appear
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-appear-mode)
#+end_src
** org-modern
Beautiful theme for org-mode buffers. Enabling globally.
*** Base org-modern settings
#+begin_src emacs-lisp
;(after! org
;  (global-org-moder-mode))
;
;(add-hook 'org-mode-hook #'org-modern-mode)
(add-hook 'org-agenda-finalize-hook #'org-modern-agenda)
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-horizontal-rule t)
  (setq org-modern-table-horizontal 0.1)
  ;(set-face-attribute 'org-modern-symbol nil :family "Iosevka")
  )
#+end_src
*** Other settings suggested on [[https://github.com/minad/org-modern][org-modern github page]]
#+begin_src emacs-lisp
(setq
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-pretty-entities t
 org-ellipsis "…")
#+end_src
** Company mode (autocomplete) in org files
#+begin_src emacs-lisp
(defun my-org-roam-company-backend (command &optional arg &rest _ignored)
  "Company backend function for org-roam links."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'my-org-roam-company-backend))
    (prefix (and (eq major-mode 'org-mode)
                 (bound-and-true-p org-roam-mode)
                 (company-grab-line "\\[\\[\\([^][]+\\)\\]\\[")))
    (candidates
     (when (looking-back "\\[\\[\\([^][]+\\)\\]\\[" (line-beginning-position) t)
       (org-roam--completing-read arg)))
    (sorted t)))

(add-hook 'org-mode-hook
          (lambda ()
            (add-to-list 'company-backends 'my-org-roam-company-backend)))
#+end_src
** org-mode: hide line numbers
#+begin_src emacs-lisp
(defun display-line-numbers--turn-off ()
  (setq display-line-numbers nil))
(add-hook 'org-mode-hook 'display-line-numbers--turn-off)
#+end_src
** org-mode: header level font sizes
#+begin_src emacs-lisp
(custom-set-faces
  '(org-document-title ((t (:inherit outline-1 :height 1.0))))
  '(org-level-1 ((t (:inherit outline-1 :height 1.0))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
)
#+end_src
** org-mode: log done time
#+begin_src emacs-lisp
(after! org
   (setq org-log-done 'time)
)
#+end_src
** Keybinding for org-element-cache-reset
#+begin_src emacs-lisp
(map! :leader
      :desc "Reset element cache" "~" #'org-element-cache-reset)
#+end_src
** Auto save for all org mode files
#+begin_src emacs-lisp
(require 'real-auto-save)
(add-hook 'org-mode-hook 'real-auto-save-mode)
#+end_src
** Default shell
I need to do this for Framework, since it has fish set as the default shell
#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
#+end_src
** Modeline settings
*** My doom-modeline settings
#+begin_src emacs-lisp
(setq doom-modeline-height 25
      doom-modeline-bar-width 5
      doom-modeline-time-icon t
      doom-modeline-continuous-word-count-modes '(markdown-mode org-mode)
      doom-modeline-modal t
      doom-modeline-modal-icon t
      doom-modeline-hud t)
#+end_src
** Show parens
#+begin_src emacs-lisp
(show-paren-mode t)
(setq show-paren-style 'mixed)
#+end_src
** Stop confirming on exit
#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src
** load path
#+begin_src emacs-lisp
(add-load-path! "~/.doom.d")
#+end_src
** beacon
#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src
** Custom splash image
#+begin_src emacs-lisp
(setq fancy-splash-image "~/Pictures/doom-banners/splashes/doom/doom-emacs-white.svg")
#+end_src
** Font settings
*** Different fonts for different computers
This loads a .el file with the hostname, which enables different font settings for the tower vs the laptop.
#+begin_src emacs-lisp
(require (intern (system-name)) nil 'noerror)
#+end_src
*** Some other font / appearance settings:
#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t)
  (setq doom-themes-enable-italic t))
(after! org
  (setq org-hide-emphasis-markers t))
#+end_src
** line spacing
#+begin_src emacs-lisp
(setq-default line-spacing 0.2)
#+end_src
** Markdown font sizes
#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.2)))))
#+end_src
** olivetti
#+begin_src emacs-lisp
(require 'olivetti)
(add-hook 'org-mode-hook 'olivetti-mode 1)
#+end_src
** global auto revert
#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src
