#+title: Config
#+property: header-args :tangle config.el
#+auto_tangle: t
#+startup: show2levels

* Doom Emacs preamble stuff
Place your private configuration here! Remember, you do not need to run 'doom
sync' after modifying this file!
** Doom identification stuff
Some functionality uses this to identify you, e.g. GPG configuration, email
clients, file templates and snippets. It is optional.
#+begin_src emacs-lisp
;;(setq user-full-name "John Doe"
;;     user-mail-address "john@doe.com")
#+end_src
** Doom font control
Doom exposes five (optional) variables for controlling fonts in Doom:

- `doom-font' -- the primary font to use
- `doom-variable-pitch-font' -- a non-monospace font (where applicable)
- `doom-big-font' -- used for `doom-big-font-mode'; use this for
  presentations or streaming.
- `doom-unicode-font' -- for unicode glyphs
- `doom-serif-font' -- for the `fixed-pitch-serif' face

See 'C-h v doom-font' for documentation and more examples of what they
accept. For example:
#+begin_src emacs-lisp
;(setq doom-font (font-spec :family "Fira Code" :size 12 :weight 'semi-light)
;     doom-variable-pitch-font (font-spec :family "Fira Sans" :size 13))
#+end_src
If you or Emacs can't find your font, use 'M-x describe-font' to look them
up, `M-x eval-region' to execute elisp code, and 'M-x doom/reload-font' to
refresh your font settings. If Emacs still can't find your font, it likely
wasn't installed correctly. Font issues are rarely Doom issues!
** Doom theme
There are two ways to load a theme. Both assume the theme is installed and
available. You can either set `doom-theme' or manually load a theme with the
`load-theme' function.
#+begin_src emacs-lisp
(setq doom-theme 'catppuccin)
(setq catppuccin-flavor 'mocha)
#+end_src
** Doom style of line numbers
This determines the style of line numbers in effect. If set to `nil', line
numbers are disabled. For relative line numbers, set this to `relative'.
#+begin_src emacs-lisp
(setq display-line-numbers-type t)
#+end_src
** Doom org directory setting
If you use `org' and don't want your org files in the default location below,
change `org-directory'. It must be set before org loads!
#+begin_src emacs-lisp
(setq org-directory "~/Sync/roam")
#+end_src
** Doom package instructions
Whenever you reconfigure a package, make sure to wrap your config in an
`after!' block, otherwise Doom's defaults may override your settings. E.g.

  (after! PACKAGE
    (setq x y))

The exceptions to this rule:

  - Setting file/directory variables (like `org-directory')
  - Setting variables which explicitly tell you to set them before their
    package is loaded (see 'C-h v VARIABLE' to look up their documentation).
  - Setting doom variables (which start with 'doom-' or '+').

Here are some additional functions/macros that will help you configure Doom.

- `load!' for loading external *.el files relative to this one
- `use-package!' for configuring packages
- `after!' for running code after a package has loaded
- `add-load-path!' for adding directories to the `load-path', relative to
  this file. Emacs searches the `load-path' when you load packages with
  `require' or `use-package'.
- `map!' for binding new keys

To get information about any of these functions/macros, move the cursor over
the highlighted symbol at press 'K' (non-evil users must press 'C-c c k').
This will open documentation for it, including demos of how they are used.
Alternatively, use `C-h o' to look up a symbol (functions, variables, faces,
etc).

You can also try 'gd' (or 'C-c c d') to jump to their definition and see how
they are implemented.
* Org-mode
** Agenda files directory
 #+begin_src emacs-lisp
(setq org-agenda-files '("~/Sync/roam/agenda"))
#+end_src
** Agenda settings
*** Global agenda settings
#+begin_src emacs-lisp
(after! org
  (setq
   org-agenda-start-day "+0d"
   org-agenda-window-setup 'current-window
   org-deadline-warning-days 2
   org-tags-exclude-from-inheritance '("thisweek" "weekend" "weekday")
   org-agenda-span 1
   org-agenda-tags-column 0
   org-agenda-skip-scheduled-if-done t
   org-agenda-skip-deadline-if-done t
   org-agenda-sorting-strategy
        '((agenda time-up habit-down priority-down category-keep)
          (todo priority-down category-keep)
          (tags priority-down category-keep)
          (search category-keep))

 ;; Suggested on org-modern github page
 org-agenda-block-separator ?─
 org-agenda-time-grid
 '((daily today require-timed)
   (800 1000 1200 1400 1600 1800 2000)
   " ┄┄┄┄┄ " "┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄")
 org-agenda-current-time-string
 "⭠ now ─────────────────────────────────────────────────"))
#+end_src
*** Define stuck projects
#+begin_src emacs-lisp
(setq org-stuck-projects
      '("TODO=\"PROJ\"&-TODO=\"DONE\"" ("TODO") nil ""))
#+end_src
*** Custom agenda commands
#+begin_src emacs-lisp
(after! org
  (setq org-agenda-custom-commands
      '(("y" tags-todo "yiyi" nil)
        ("h" "Habits"
            ((agenda ""
                ((org-agenda-files '("~/Sync/roam/agenda/habits_org.org"))))))
        ("A" "Main agenda"
            ((agenda ""
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'deadline))
                 (org-agenda-overriding-header "Scheduled\n")))
            (tags-todo "thisweek"
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'scheduled 'deadline))
                 (org-agenda-overriding-header "\nThis Week\n")))
            ;(tags-todo "weekend"
                ;((org-agenda-skip-function
                  ;`(org-agenda-skip-entry-if 'todo 'done 'scheduled 'deadline))
                 ;(org-agenda-overriding-header "\nWeekend\n")))
            ))
            ;((org-agenda-tag-filter-preset '("-habit"))))
        ("w" "Weekend"
            ((agenda ""
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'deadline))
                 (org-deadline-warning-days 0)
                 (org-agenda-overriding-header "WEEKEND AGENDA\n\nToday")))
             ;; (agenda ""
             ;;    ((org-agenda-skip-function
             ;;      `(org-agenda-skip-entry-if 'todo 'done))
             ;;     (org-deadline-warning-days 1)
             ;;     (org-agenda-prefix-format "  %s ")
             ;;     (org-agenda-entry-types `(:deadline))
             ;;     (org-agenda-overriding-header "\nDue soon")))
             (tags-todo "+weekend-fun-errands"
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'scheduled))
                 (org-agenda-sorting-strategy `(priority-down deadline-up category-keep))
                 (org-agenda-overriding-header "\nWeekend")))
             ))
             ;(tags-todo "fun"
                ;((org-agenda-overriding-header "\nFun")))
             ;(tags-todo "+errands+weekend"
                ;((org-agenda-skip-function
                  ;`(org-agenda-skip-entry-if 'todo 'done 'scheduled))
                 ;(org-agenda-overriding-header "\nWeekend Errands")))
            ;((org-agenda-tag-filter-preset '("-habit"))))
        ("W" "This week"
            ((agenda ""
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'deadline))
                 (org-deadline-warning-days 0)
                 (org-agenda-overriding-header "THIS WEEK\n\nToday")))
             (agenda ""
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done))
                 (org-deadline-warning-days 2)
                 (org-agenda-prefix-format "  %s ")
                 (org-agenda-entry-types `(:deadline))
                 (org-agenda-sorting-strategy `(deadline-up))
                 (org-agenda-overriding-header "\nDue soon")))
            (tags-todo "thisweek"
                ((org-agenda-skip-function
                  `(org-agenda-skip-entry-if 'todo 'done 'scheduled 'deadline))
                 (org-agenda-sorting-strategy `(deadline-up priority-down category-up))
                 (org-agenda-overriding-header "\nThis week")))
            ;(tags-todo "+errands+thisweek"
                ;((org-agenda-overriding-header "\nErrands")))
            ))
            ;((org-agenda-tag-filter-preset '("-habit"))))
        )
    )
  )
#+end_src
*** auto-save when quitting org agenda
#+begin_src emacs-lisp
(advice-add 'org-agenda-quit :before 'org-save-all-org-buffers)
#+end_src
*** auto-save all org agenda buffers
#+begin_src emacs-lisp
(add-hook 'auto-save-hook 'org-save-all-org-buffers)
#+end_src
*** DEPRECATED org-mode agenda don't show completed items
#+begin_src emacs-lisp
;(setq org-agenda-skip-scheduled-if-done t)
;(setq org-agenda-skip-deadline-if-done t)
#+end_src
*** DEPRECATED open org agenda in current window
#+begin_src emacs-lisp
;(after! org
;  (setq org-agenda-window-setup 'other-window)
;  )
#+end_src
** org-mode: TODO states
#+begin_src emacs-lisp
(after! org
  (setq org-todo-keywords
      '((sequence "TODO(t)" "WAITING(w)" "PROJ(p)" "SOMEDAY(s)" "|" "DONE(d)" "CANCELED(c)")))
  )
#+end_src
** org-appear
#+begin_src emacs-lisp
(add-hook 'org-mode-hook 'org-appear-mode)
#+end_src
** org-mode capture
*** Keybindings
#+begin_src emacs-lisp
(map! :leader
      :desc "Pop up scratch buffer" "X" #'doom/open-scratch-buffer
      :desc "Org Capture" "x" #'org-capture)
#+end_src
*** Templates
#+begin_src emacs-lisp
(after! org
  (setq org-capture-templates
      '(("t" "Todo" entry (file "~/Sync/roam/agenda/inbox.org")
         "* TODO %?")
        ("T" "Todo (clipboard)" entry (file "~/Sync/roam/agenda/inbox.org")
         "* TODO %? (notes)\n%x")
        ("d" "Todo (document)" entry (file "~/Sync/roam/agenda/inbox.org")
         "* TODO %? (notes)\n%a")
        ("i" "Todo (interactive)" entry (file "~/Sync/roam/agenda/inbox.org")
         "* TODO %? (notes)\n%^C")))
)
#+End_src
** org-modern
Beautiful theme for org-mode buffers. Enabling globally.
*** Base org-modern settings
#+begin_src emacs-lisp
;(after! org
;  (global-org-moder-mode))
;
;(add-hook 'org-mode-hook #'org-modern-mode)
(add-hook 'org-agenda-finalize-hook #'org-modern-agenda)
(use-package! org-modern
  :hook (org-mode . org-modern-mode)
  :config
  (setq org-modern-horizontal-rule t)
  (setq org-modern-table-horizontal 0.1)
  ;(set-face-attribute 'org-modern-symbol nil :family "Iosevka")
  )
#+end_src
*** Other settings suggested on [[https://github.com/minad/org-modern][org-modern github page]]
#+begin_src emacs-lisp
(setq
 org-auto-align-tags nil
 org-tags-column 0
 org-catch-invisible-edits 'show-and-error
 org-pretty-entities t
 org-ellipsis "…")
#+end_src
** org-roam
#+begin_src emacs-lisp
(use-package org-roam
;  :ensure t
  :custom
  (org-roam-directory "~/Sync/roam")
  (org-roam-capture-templates
   '(("d" "default" plain
      "%?"
      :if-new (file+head "${slug}.org" "#+title: ${title}\n#+date: %U\n")
      :unnarrowed t)))
  :config
  (org-roam-setup))
#+end_src
** org-roam-ui
*** Basic settings
Settings from https://github.com/org-roam/org-roam-ui#doom
#+begin_src emacs-lisp
(use-package! websocket
  :after org-roam)

(use-package! org-roam-ui
  :after org-roam
  :config
  (setq org-roam-ui-sync-theme t
        org-roam-ui-follow t
        org-roam-ui-update-on-save t
        org-roam-ui-open-on-start t))
#+end_src
*** Map keybinding for org-roam-ui
#+begin_src emacs-lisp
(map! :after org-roam-ui
      :leader
      :desc "Org-roam UI"
      "n r u" #'org-roam-ui-open)
#+end_src
*** Unmap org-mode-graph because it sucks
#+begin_src emacs-lisp
(map! :leader
      "n r g" nil)
#+end_src
** Company mode (autocomplete) in org files
#+begin_src emacs-lisp
(defun my-org-roam-company-backend (command &optional arg &rest _ignored)
  "Company backend function for org-roam links."
  (interactive (list 'interactive))
  (cl-case command
    (interactive (company-begin-backend 'my-org-roam-company-backend))
    (prefix (and (eq major-mode 'org-mode)
                 (bound-and-true-p org-roam-mode)
                 (company-grab-line "\\[\\[\\([^][]+\\)\\]\\[")))
    (candidates
     (when (looking-back "\\[\\[\\([^][]+\\)\\]\\[" (line-beginning-position) t)
       (org-roam--completing-read arg)))
    (sorted t)))

(add-hook 'org-mode-hook
          (lambda ()
            (add-to-list 'company-backends 'my-org-roam-company-backend)))
#+end_src
** Org-auto-tangle
#+begin_src emacs-lisp
(use-package! org-auto-tangle
    :defer t
    :hook (org-mode . org-auto-tangle-mode)
    :config
    (setq org-auto-tangle-default t)
)
#+end_src
** org-mode: hide line numbers
#+begin_src emacs-lisp
(defun display-line-numbers--turn-off ()
  (setq display-line-numbers nil))
(add-hook 'org-mode-hook 'display-line-numbers--turn-off)
#+end_src
** org-mode: header level font sizes
#+begin_src emacs-lisp
(custom-set-faces
  '(org-document-title ((t (:inherit outline-1 :height 1.0))))
  '(org-level-1 ((t (:inherit outline-1 :height 1.0))))
  '(org-level-2 ((t (:inherit outline-2 :height 1.0))))
  '(org-level-3 ((t (:inherit outline-3 :height 1.0))))
  '(org-level-4 ((t (:inherit outline-4 :height 1.0))))
  '(org-level-5 ((t (:inherit outline-5 :height 1.0))))
)
#+end_src
** org-mode: log done time
#+begin_src emacs-lisp
(after! org
   (setq org-log-done 'time)
   )
#+end_src
** org-habit
#+begin_src emacs-lisp
(use-package! org-habit
  :after org
  :config
  (setq org-habit-following-days 7
        org-habit-preceding-days 15
        org-habit-show-habits t
        org-habit-show-habits-only-for-today nil
        org-habit-graph-window-ratio 0.2
        org-habit-graph-padding 1))
#+end_src
** Searching org-roam files with consult-ripgrep
Taken from https://baty.net/2022/searching-org-roam-files/
#+begin_src emacs-lisp
(defun josh/search-roam ()
  "Run consult-ripgrep on the org roam directory"
  (interactive)
  (consult-ripgrep org-roam-directory))

(map! :leader
      (:prefix ("s" . "search")
       :desc "Search org-roam files" "R" #'josh/search-roam))
#+end_src
** Keybinding for org-element-cache-reset
#+begin_src emacs-lisp
(map! :leader
      :desc "Reset element cache" "~" #'org-element-cache-reset)
#+end_src
** Auto save for all org mode files
#+begin_src emacs-lisp
(require 'real-auto-save)
(add-hook 'org-mode-hook 'real-auto-save-mode)
#+end_src
** DEPRECATED
*** org-bullets
#+begin_src emacs-lisp
;(after! org
;  (require 'org-bullets)
;  (add-hook 'org-mode-hook (lambda () (org-bullets-mode 1)))
;  )
#+end_src
* Other custom settings
** Projectile projects
Defining projects
#+begin_src emacs-lisp
;(projectile-add-known-project “~/Sync/Logseq”)
#+end_src
** Default shell
I need to do this for Framework, since it has fish set as the default shell
#+begin_src emacs-lisp
(setq shell-file-name (executable-find "bash"))
#+end_src
** Modeline settings
*** Doom Nano Modeline
#+begin_src emacs-lisp
;(use-package! doom-nano-modeline
;  :config
;  (doom-nano-modeline-mode 1)
;  (global-hide-mode-line-mode 1))
#+end_src
*** My doom-modeline settings
#+begin_src emacs-lisp
(setq doom-modeline-height 25
      doom-modeline-bar-width 5
      doom-modeline-time-icon t
      doom-modeline-continuous-word-count-modes '(markdown-mode org-mode)
      doom-modeline-modal t
      doom-modeline-modal-icon t
      doom-modeline-hud t)
#+end_src
** For the love of god stop putting shit in my clipboard
Press super-c to copy without affecting the kill ring. Press super-x or super-v to cut or paste. On OS X, use ⌘-c, ⌘-v, ⌘-x.
#+begin_src emacs-lisp
(require 'simpleclip)
(simpleclip-mode 1)
(map! "C-S-c" #'simpleclip-copy
      "C-S-v" #'simpleclip-paste
      "C-S-x" #'simpleclip-cut)
#+end_src
** Show parens
#+begin_src emacs-lisp
(show-paren-mode t)
(setq show-paren-style 'mixed)
#+end_src
** Stop confirming on exit
#+begin_src emacs-lisp
(setq confirm-kill-emacs nil)
#+end_src
** load path
#+begin_src emacs-lisp
(add-load-path! "~/.doom.d")
#+end_src
** beacon
#+begin_src emacs-lisp
(beacon-mode 1)
#+end_src
** Custom splash image
#+begin_src emacs-lisp
(setq fancy-splash-image "~/Pictures/doom-banners/splashes/doom/doom-emacs-white.svg")
#+end_src
** Font settings
*** Different fonts for different computers
This loads a .el file with the hostname, which enables different font settings for the tower vs the laptop.
#+begin_src emacs-lisp
(require (intern (system-name)) nil 'noerror)
#+end_src
*** Some other font / appearance settings:
#+begin_src emacs-lisp
(after! doom-themes
  (setq doom-themes-enable-bold t)
  (setq doom-themes-enable-italic t))
(after! org
  (setq org-hide-emphasis-markers t))
#+end_src
** line spacing
#+begin_src emacs-lisp
(setq-default line-spacing 0.2)
#+end_src
** Markdown font sizes
#+begin_src emacs-lisp
(custom-set-faces
 '(markdown-header-face ((t (:inherit font-lock-function-name-face :weight bold :family "variable-pitch"))))
 '(markdown-header-face-1 ((t (:inherit markdown-header-face :height 1.6))))
 '(markdown-header-face-2 ((t (:inherit markdown-header-face :height 1.4))))
 '(markdown-header-face-3 ((t (:inherit markdown-header-face :height 1.2)))))
#+end_src
** olivetti
#+begin_src emacs-lisp
(require 'olivetti)
(add-hook 'org-mode-hook 'olivetti-mode 1)
#+end_src
** global auto revert
#+begin_src emacs-lisp
(global-auto-revert-mode 1)
#+end_src
* Deprecated
** deft
** nov - epub reader
#+begin_src emacs-lisp
;(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
;(setq nov-text-width t)
;(setq visual-fill-column-center-text t)
;(add-hook 'nov-mode-hook 'visual-line-mode)
;(add-hook 'nov-mode-hook 'visual-fill-column-mode)
#+end_src
** A Doom thing; is this necessary?
#+begin_src emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-
#+end_src
** Stop showing emojies for certain characters
*** Attempt 1
/Holy crap I might have finally figured it out./ This code is from [[https://tecosaur.github.io/emacs-config/config.html][here]].
#+begin_src emacs-lisp
;(defvar emojify-disabled-emojis
;  '("☑", "©", "™", "✔", "❓", "⏩", "⏪"
;  "Characters that should never be affected by `emojify-mode'.")

;(defadvice! emojify-delete-from-data ()
;  "Ensure `emojify-disabled-emojis' don't appear in `emojify-emojis'."
;  :after #'emojify-set-emoji-data
;  (dolist (emoji emojify-disabled-emojis)
;    (remhash emoji emojify-emojis))))
#+end_src
*** Attempt 2
#+begin_src emacs-lisp
;(add-hook 'org-mode-hook (lambda ()
;  "Beautify Org Checkbox Symbol"
;  (push '("[ ]" . "☐") prettify-symbols-alist)
;  (push '("[x]" . "🗷" ) prettify-symbols-alist)
;  (push '("[-]" . "" ) prettify-symbols-alist)
;  (prettify-symbols-mode)))
#+end_src
** DEPRECATED Pandoc import
#+begin_src emacs-lisp
;(use-package! org-pandoc-import :after org)
#+end_src
** DEPRECATED emojies
#+begin_src emacs-lisp
;(use-package emojify
;  :hook (after-init . global-emojify-mode))
#+end_src
** DEPRECATED insert date
From [[https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/doom/config.org#set-font-sizes-for-each-header-level-in-org][here]].
#+begin_src emacs-lisp
;(defun dt/insert-todays-date (prefix)
;  (interactive "P")
;  (let ((format (cond
;                 ((not prefix) "%Y-%m-%d")
;                 ((equal prefix '(4)) "%m-%d-%Y")
;                 ((equal prefix '(16)) "%A, %B %d, %Y"))))
;    (insert (format-time-string format))))

;(require 'calendar)
;(defun dt/insert-any-date (date)
;  "Insert DATE using the current locale."
;  (interactive (list (calendar-read-date)))
;  (insert (calendar-date-string date)))

;(map! :leader
;      (:prefix ("i d" . "Insert date")
;        :desc "Insert any date" "a" #'dt/insert-any-date
;        :desc "Insert todays date" "t" #'dt/insert-todays-date))
#+end_src
** DEPRECATED treemacs
#+begin_src emacs-lisp
;(require 'treemacs)
;; (setq treemacs-no-png-images t)
;(setq doom-themes-treemacs-theme "doom-colors")
#+end_src
** DEPRECATED calfw
#+begin_src emacs-lisp
;(require 'calfw)
;(require 'calfw-org)
;(setq cfw:org-agenda-schedule-args
;      '((org-agenda-files `("~/Sync/roam/habits_org.org"))))
#+end_src
** DEPRECATED Chinese font settings
#+begin_src emacs-lisp
;(set-fontset-font "fontset-default" 'han (font-spec :family "Sarasa Gothic CL" :size 14))
;(defun init-cjk-fonts()
;  (dolist (charset '(kana han cjk-misc bopomofo))
;    (set-fontset-font (frame-parameter nil 'font)
;      charset (font-spec :family "Noto Sans Mono CJK SC" :size 36))))
;(add-hook 'doom-init-ui-hook 'init-cjk-fonts)
#+end_src
** DEPRECATED minimap
From [[https://gitlab.com/dwt1/dotfiles/-/blob/master/.config/doom/config.org#set-font-sizes-for-each-header-level-in-org][here]].
#+begin_src emacs-lisp
;(setq minimap-window-location 'right)
;(map! :leader
;      (:prefix ("t" . "toggle")
;       :desc "Minimap-mode" "m" #'minimap-mode))
#+end_src
